### ISSUE TITLE
Non-destructive bucketing endpoint

### ISSUE THREAD

**Issue by dlanger** [seatgeek/sixpack#108]
We do a number of experiments where we only bucket a portion of the population - so at the point of bucketing we apply some business logic, and only call `participate` on the users we want in the experiment.  

Downstream from there - and on a different system - we'd like to just call `participate` again on all users to get the bucket they're in, but that would also bucket the users who we chose not to earlier, so we have to keep that logic in multiple places. I'd be nice if in that second spot we could call `get_bucket` which would return the bucket a user is in, but not bucket them if they haven't yet been bucketed.

**Comment by adrianmaurer** [comment]
+1

**Comment by dlanger** [comment]
Pretty sure this is solved by setting the `prefetch` argument to `True`.
