### ISSUE TITLE
Can't start sixpack with gunicorn

### ISSUE THREAD

**Issue by waziers** [seatgeek/sixpack#155]
On Ubuntu, and on Mac OS X I 've tried the following with python 2.7.8:

```
pip install gevent gunicorn sixpack
gunicorn --access-logfile - -w 2 --worker-class=gevent sixpack.web:start
```

The gunicorn command just hangs and there is no output, and the web service is not available. I've tried passing environment variables in order to explicitly set the config file, web port, debug level, etc.. but with no success. If I got into site-packages and change the source of ```sixpack/web.py``` to include print statements inside the start function, they never show up.

I'm able to run the sixpack-web binary without a problem and load the interface in the browesr. This leads me to believe this isn't a sixpack issue but rather a gunicorn/sixpack issue.

I'm fairly certain I'm following the steps in the documentation of sixpack, gunicorn, and flask to do this successfully. 

Library versions:

```
gevent (1.0.1)
gunicorn (19.1.1)
Sixpack (2.0.2)
```

**Comment by josegonzalez** [comment]
I'm unable to replicate this issue running the xact commands you are running. Sorry for the late response. Feel free to comment if you are still having this issue.
