### ISSUE TITLE
Deterministic participation based on a custom parameter

### ISSUE THREAD

**Issue by clarkbk** [seatgeek/sixpack#161]
**Disclaimer:** Might be a dumb idea, but here goes.  I'll start with my intended use case:

I want to A/B test title tag formats for a particular page type, because SEO.  It isn't suitable to set up a Sixpack experiment that determines participation on a per-client level, because I will want to measure whether the title tag change effects SERP ranks and therefore traffic.  In order for that to be possible, I need a guarantee that Google & other crawlbots will all be getting the same variant of the page.

What if a Sixpack experiment could be configured in a deterministic way based using an extra parameter, taken from the context of the experiment?  For example, I could include in the `/participate` call a custom parameter that contains the page ID (say, a performer ID, in SeatGeek's case).  Sixpack would do some participating magic and always return the same variant for the given page ID.  My experiment would now be consistent between pages (instead of between clients).

Is this a bad/impossible/frivolous idea?

**Comment by erwaller** [comment]
This *may* already be possible.

> Sixpack would do some participating magic and always return the same variant for the given page ID

This part is easy b/c you're free to specify the sixpack client id which sixpack uses to deterministically choose an alternative.

The piece I don't understand is: how do you want to measure conversion? Total inbound traffic to a given title format? I don't think that would possible b/c each "page id" can only convert once. Sixpack only has the concept of singular conversion, ie. a participant has converted or they haven't.

**Comment by clarkbk** [comment]
I hadn't really thought about conversion in my particular use case.  I had figured Sixpack wouldn't be useful for comparing traffic/entrances, but the 1-conversion-per-page scheme that you described obviously wouldn't be very useful at all.  Nevertheless, the main thing I think I wanted to be able to do was use Sixpack to randomly and roughly equivalently assign alternatives between pages, so it's good to know that that might work.  Even just using this to set up our split test is probably better than other hacky alternatives that we might use without Sixpack – like switching title tag formats based on odd/even performer IDs.  (Although I guess I'll need to figure out how to query Redis to find which page/performer IDs get assigned to which variant?)

@erwaller Feel free to close this issue if you think there's nothing to be learned from this use case.  Sounds like the only thing that might be interesting is the flexibility for Sixpack to account for >1 conversions per client, which is prob a different/separate issue.

**Comment by erwaller** [comment]
Oh ok, yeah if you just want a strategy for splitting pages or whatever into alternative buckets deterministically based on some input text you can use the algorithm within sixpack: https://github.com/seatgeek/sixpack/blob/3a185aa642baf8f50ab082a8a5ed9a0dc6da7a3e/sixpack/models.py#L343. I can show you how to implement the same thing in PHP or JS or whatever. I wouldn't actually bother to use sixpack because you'll just incur a request to the server on every pageview for no real benefit.

**Comment by erwaller** [comment]
Btw, it's the same strategy as `id % 2`, it's just slightly nicer in that the input doesn't have to be an integer and it ensures that if you run multiple experiments, the same input values won't always be mapped to the same alternative bucket (ie. in the mod strategy, "2" will always get the first alternative).

**Comment by clarkbk** [comment]
K, cool.  That makes sense.  Thanks @erwaller.
