### ISSUE TITLE
Redis requirements update

### ISSUE THREAD

**Issue by caxap** [seatgeek/sixpack#162]
Is there any reason why it requires Redis v2.9.0 explicitly? Can it be >=2.9.0 instead? (actually it's same for hiredis).

**Comment by zackkitzmiller** [comment]
>= 2.9.0 is fine.

**Comment by caxap** [comment]
Any updates on requirements.txt ?

**Comment by zackkitzmiller** [comment]
Feel free to pull requests.

On Thu, Jan 29, 2015 at 8:05 AM, Maxim Kamenkov <notifications@github.com>
wrote:

> Any updates on requirements.txt ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seatgeek/sixpack/issues/162#issuecomment-72020435>.
>



-- 
--
Zack Kitzmiller
SeatGeek <https://seatgeek.com>
