### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Valve** [seatgeek/sixpack#169]
What's the state of authentication in sixpack server?  How can I limit the access to both sixpack server and sixpack web?

IP based whitelisting won't work for heroku or any cloud-based, auto-provisioned servers/containers, because the IPs assigned to them are dynamic.

**Comment by zackkitzmiller** [comment]
We basically don't need to protect sixpack-server, and in this would break the JS client. 

Sixpack web can be put behind any sort of auth you like, we use Github oAuth at SeatGeek.

**Comment by Valve** [comment]
thanks
