### ISSUE TITLE
sixpack-web http-500 status

### ISSUE THREAD

**Issue by nkkrishnak** [seatgeek/sixpack#172]
Hello All,

 I am new to sixpack.Just installed sixpack.

Sixpack server works fine.
 * Running on http://0.0.0.0:5000/
- - [29/Apr/2015 08:51:21] "GET / HTTP/1.1" 200 -
- - [29/Apr/2015 08:51:21] "GET /favicon.ico HTTP/1.1" 200 -

Sixpack-web throws http-500 errors on request

SIXPACK_CONFIG=/etc/sixpack/config.yml sixpack-web
 * Running on http://0.0.0.0:5001/
[29/Apr/2015 08:51:23] "GET / HTTP/1.1" 500 -
[29/Apr/2015 08:51:23] "GET /static/gen/sixpack.css?83082c39 HTTP/1.1" 500 -
[29/Apr/2015 08:51:23] "GET /static/gen/sixpack.js?fd5af139 HTTP/1.1" 500 -
[29/Apr/2015 08:51:23] "GET /static/img/favicon.png HTTP/1.1" 500 -

Kindly help me out.Thanks in advance.

**Comment by zackkitzmiller** [comment]
Can you run Sixpack in debug mode so we can get the actual stacktrace? This will help debug the issue.

**Comment by alexcasalboni** [comment]
I had the same problem. You need to configure the *secret_key* parameter in your yaml configuration (comment reads "*Random key (any string is valid, required for sixpack-web to run)*").
