### ISSUE TITLE
Force parameter

### ISSUE THREAD

**Issue by huyhoang1990** [seatgeek/sixpack#179]
Sixpack worked well without having "force" parameter in url.

I used force param look like this 
https://<<my_domain>>/participate?client_id=2u7psfke1rpp4etk31e8vnibu4&experiment=loa-bluetooth&alternatives=yes&alternatives=no&user_agent=Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_9_4)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F43.0.2357.124%20Safari%2F537.36&callback=sixpack.callback1&force=yes

in the dashboard, i cannot see the increment of number.

Please help me to check it

**Comment by zackkitzmiller** [comment]
The `force` param intentionally doesn't record participations to avoid mucking up the data. It's only available so that you can see all of the available options easily.
