### ISSUE TITLE
Any plans to release a newer version to pypi? I can't run sixpack on a specific port

### ISSUE THREAD

**Issue by altryne** [seatgeek/sixpack#182]
Hi guys,
trying to see if sixpack is good enough for production for us.
Got a bug right from the bat, and it turns out you guys already fixed it here https://github.com/seatgeek/sixpack/commit/fb74376aa961eb785a20a9c2eeef3a33ff042ea8

But the pypi release is 10 months old, and it doesn't have this fix, and our default port is 5000, which means we have to change ports for sixpack. 

When is the next planned release to pypi?

**Comment by zackkitzmiller** [comment]
I can release today.

**Comment by altryne** [comment]
Thank you!

**Comment by zackkitzmiller** [comment]
Sixpack 2.0.3 is now available on pypi.
