### ISSUE TITLE
What is the motivation to not allow the traffic fraction to change?

### ISSUE THREAD

**Issue by nickveenhof** [seatgeek/sixpack#191]
In our application we have the possibility to change the traffic fraction. Since the only responsibility sixpack has is to not include the user in the test, I don't see why we wouldn't allow to change this value during the tests itself.

The reason for this is simple, you first start with a small subset of customers, say 10%. Afterwards you come more confident in your test and you want to raise it to 20%. The only thing that changes are the amount of people that get included in the test. The numbers do not change and the statistical influence of this change is zero.

Thoughts?

**Comment by nickveenhof** [comment]
Here's a PR on one of our own branches of sixpack: https://github.com/blackskad/sixpack/pull/2

The only oddity I could find while looking at the code would be that the percentage could be changed in the interim so that the value, when showing the experiment in sixpack-web is not correct. This is however not a big deal. You could for example keep track if the number was changed during the course of the experiment and even provide historic data when it was changed. I understand this might cause conflicts with admins who want to know exactly when a certain amount of traffic was excluded so I'd love some input here as to what we could do to make this more flexible.

**Comment by zackkitzmiller** [comment]
@nickveenhof that change looks good. Would you mind writing a unit test, and opening a PR against this repo

**Comment by nickveenhof** [comment]
On it. I really appreciate your responsiveness @zackkitzmiller!

**Comment by nickveenhof** [comment]
Added a PR #192

**Comment by nickveenhof** [comment]
Any update?

**Comment by josegonzalez** [comment]
Closed by #192.
