### ISSUE TITLE
Out of the box, getting 400s for participate endpoint

### ISSUE THREAD

**Issue by rue-kpickering** [seatgeek/sixpack#194]
After setting up sixpack for the first time, I'm playing with the default endpoints provided in the docs and getting a "missing arguments" response.

Here's the curl:
curl http://localhost:5000/participate?experiment=button_color&alternatives=red&alternatives=blue&client_id=12345678-1234-5678-1234-567812345678

Tried a bunch of different permutations of parameters, as well.

Here's the log from sixpack on the inbound request:
127.0.0.1 - - [19/Aug/2015 13:23:06] "GET /participate?experiment=new-header HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:25:39] "GET /participate?experiment=button_color HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:27:48] "GET /participate?experiment=button HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:28:00] "GET /participate?experiment=button HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:38:31] "GET /participate?experiment=new-header HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:38:57] "GET /participate?experiment=new-header HTTP/1.1" 400 -
127.0.0.1 - - [19/Aug/2015 13:40:14] "GET /convert?experiment=new-header HTTP/1.1" 400 -

And, all occurances give "missing arguments":
{"status": "failed", "message": "missing arguments"}

I might be missing something simple here, but I dove into the code, and it looks like I should be passing all the required parameters in the URI.

Thanks!

**Comment by zackkitzmiller** [comment]
All calles to participate require at least two `alternative`s, `experiement` name, and `client_id`. Seems you're missing those in your subsequent calls.

**Comment by rue-kpickering** [comment]
The request I'm using should be valid: 
curl http://localhost:5000/participate?experiment=button_color&alternatives=red&alternatives=blue&client_id=12345678-1234-5678-1234-567812345678

gives:

127.0.0.1 - - [19/Aug/2015 13:53:17] "GET /participate?experiment=button_color HTTP/1.1" 400 -
And...
{"status": "failed", "message": "missing arguments"}

**Comment by rue-kpickering** [comment]
Figured it out. If you put an " ' " around the string in curl, it works. My bad. Thanks for the assist.

You might want to edit the docs, though!
