### ISSUE TITLE
How can I select how many times an alternative appears? 

### ISSUE THREAD

**Issue by wildlifechorus** [seatgeek/sixpack#213]
I want to be able to weight the alternatives, but I cant find any param that allows me to do that.
I really don't understand how the alternatives are "assigned", is it totally random?

**Comment by zackkitzmiller** [comment]
Alternatives are assigned using a deterministic algorithm  based on the `client_id`. This allows for clients to "predict" which alternative is going to be assigned. Relevant code is [here](https://github.com/seatgeek/sixpack/blob/master/sixpack/models.py#L353).

**Comment by wildlifechorus** [comment]
I was checking this http://facebook.github.io/planout/docs/random-operators.html

WeightedChoice

**Comment by wildlifechorus** [comment]
Not sure if I should post on this thread but I can't figure out how to set Confidence as well. No param for that

**Comment by josegonzalez** [comment]
This project doesn't implement the planout algorithm.
