### ISSUE TITLE
pip version lags behind master

### ISSUE THREAD

**Issue by mdressman** [seatgeek/sixpack#218]
Please release a new version, I just spent entirely too much time tracking down a bug that was fixed in #201 
I didn't realize I didn't have this fix as I've got the latest version installed.
Pretty frustrating. 

Is there a reason the versioning process isn't done explicitly as part of the merge-to-master process?

Thank you!

**Comment by josegonzalez** [comment]
To be honest, we actually run master at work, so releasing hasn't been a big "priority" so to speak. I'll speak to @zackkitzmiller about this in person and figure out what we need to do to get this to be a normal thing (I already have a script to handle python releases, so it shouldn't be too hard once we figure that out).

**Comment by mdressman** [comment]
Hi, any updates?

**Comment by josegonzalez** [comment]
Hi! I just got perms to the pypi package, so after the hackathon - gotta make a dashboard! - I'll do the thing. Thanks for being patient.

**Comment by josegonzalez** [comment]
Released! I'll be better about this in the future, and will try and go over our open issues/PRs this week when I get a chance (no promises, I have a cat to pet and she gets mean if I don't pet her every 10 minutes :cat: ).

Thanks again for being patient!

**Comment by mdressman** [comment]
awesome, thanks @josegonzalez
