### ISSUE TITLE
Can't convert if participate with '&force='

### ISSUE THREAD

**Issue by lenacom** [seatgeek/sixpack#220]
We use sixpack 2.0.3.

It's possible to participate with a forced alternative:
/participate?experiment=mytest1&alternatives=one&alternatives=two&client_id=123456789&force=one
Response:
{
    "status": "ok",
    "alternative": 
{
    "name": "one"
},
"experiment": 
    {
        "name": "mytest1"
    },
   "client_id": "123456789"
}

However conversion doesn't work:
/convert?experiment=mytest1&client_id=123456789
Response:
{
    "status": "failed",
    "message": "this client was not participaing"
}

**Comment by zackkitzmiller** [comment]
Calling `force` intentionally skips the data store and as such the participation wasn't recorded. Force is intended to preview what alternatives look like in production. This is the extended behavior.

**Comment by joshhunt** [comment]
@zackkitzmiller I get the rationale behind this - force is intended for previewing.

However, the are usecases where we might want to force certain users into a segment and still record the results, like:

 * We want to force all employees into the experiment
 * We use a CDN like Akamai which prevents us from making per-user modifications on the server, but Akamai supports segmentation. So the decision on which segment the user is in would actually be done by Akamai and then we just use sixpack to record the conversions.

Is this something you would be open to incorporating, or reviewing a PR for?
