### ISSUE TITLE
Expirements not showing in Web

### ISSUE THREAD

**Issue by gray419** [seatgeek/sixpack#226]
Sixpack 2.2.0
I'm running sixpack on :5000 and sixpack-web :5001 on a local vagrant instance. Forwarding ports 5000 and 5001.

curl 'http://localhost:5000/participate?experiment=new-header&alternatives=red&alternatives=blue&client_id=123'

```json
{
  "status": "ok",
  "alternative": {
    "name": "red"
  },
  "experiment": {
    "name": "new-header"
  },
  "client_id": "123"
}
```

curl http://localhost:5001/experiments.json
```json
{
  "experiments": []
}
```
Nothing shows up in the web dashboard or experiments.json endpoint.

**Comment by zackkitzmiller** [comment]
Do you always get `red` regardless of `client_id`? My initial suspicion is that for some reason the participation isn't being recorded in Redis.

**Comment by gray419** [comment]
Just ran again
curl 'http://localhost:5000/participate?experiment=new-header&alternatives=red&alternatives=blue&client_id=1234'
```json
{
  "status": "ok",
  "alternative": {
    "name": "blue"
  },
  "experiment": {
    "name": "new-header"
  },
  "client_id": "1234"
}
```

I'm suspicious of redis too. The box is running
 `Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=49ffd7ce21c94625`

Do you know what the redis key is, I can try and query in the cli to see if anything is in there

**Comment by zackkitzmiller** [comment]
The entire keyspace is defined [here](https://github.com/seatgeek/sixpack/blob/master/KEYSPACE).

**Comment by gray419** [comment]
These are the redis query results
```
127.0.0.1:6379> GET e
(nil)
127.0.0.1:6379> GET sixpack:e
(nil)
127.0.0.1:6379> HGETALL e:new-header
(empty list or set)
```

**Comment by gray419** [comment]
I re-created a VM and made sure to install python and redis BEFORE installing sixpack. That seemed to fix the issue!
