### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by PezCoder** [seatgeek/sixpack#228]
### Please Update the documentation regarding these:

1. There is no documentation about excluded_clients that I came across when i tried to delete cookie & sent the GET request again, it didn't mark it as another valid user rather put it in excluded clients.
Please explain this.

2. Is there an interactive dashboard. Is the experiments.json the only way to see all the info about the clients.
Note: I'm using php version of sixpack

**Comment by josegonzalez** [comment]
Regarding the dashboard, https://github.com/seatgeek/sixpack#dashboard

**Comment by PezCoder** [comment]
@josegonzalez Dashboard working.. looks like I had a permission issue.. 
What about the excluded_client ?

**Comment by PezCoder** [comment]
Can i change the traffic fraction on the fly with dashboard?looks like we can just make it winner i.e 100%... If i want to chamge the fraction, do i have to make another build & puah it to prod with the changed fraction ??

**Comment by PezCoder** [comment]
@josegonzalez  What is the tracking_fraction order ? if i send alternatives as ['new','old'] is it the traffic fraction of new ?

**Comment by josegonzalez** [comment]
`traffic_fraction` Is for whether or not the traffic is allowed to select an alternative or whether it must be in the control. For instance, you may only want to send a percentage of traffic through the ab test, and that is what that option is for. We do not implement weighted alternatives at this time.
