### ISSUE TITLE
Intermittent Timeout Issues

### ISSUE THREAD

**Issue by russelltaylor05** [seatgeek/sixpack#229]
Just got sixpack up and running, but I'm seeing 50% - 75% of participate requests timeout in production. Here is the error I'm seeing on the client side:

```
Error: request timed out at http://cssmenumaker.dev/sites/all/themes/cssmenu/js/sixpack.js?o6pqly:171:29
```

Line 171 of the javascript client looks like this: 
```
    var _request = function(uri, params, timeout, callback) {
        var timed_out = false;
        var timeout_handle = setTimeout(function () {
            timed_out = true;
            return callback(new Error("request timed out"));
        }, timeout); // <--- Line 171
```
I've been trying to isolate the problem with either the client or the server, but results or so sporadic it's difficult to pin down.

### Server
EC2 t2.micro instance on AWS. CPU levels never seem to spike so I don't think i'm taxing the server too much.  My production website does receive 10,000+ visitors a day so the participate endpoint is definitely getting pinged every second or so. 

Here is the participate endpoint:

```
http://52.90.248.164:5000/participate?client_id=64935fe6-ac98-4447-a26f-4840c6956eb0&experiment=homepage-layout&alternatives=original&alternatives=variation
```

### Client
I'm using the Sixpack javascript client.

### Python Setup

I'm not that familiar with Python, but this is how I called my scripts to run in the background:

```
sudo SIXPACK_CONFIG=~/sixpack.yml sixpack &
sudo SIXPACK_CONFIG=~/sixpack.yml sixpack-web &
```

The docs mentioned running `gunicorn` in production. Not sure if this would be related to my timeout issues.

### Final Thoughts

My gut feeling is that my python environment isn't setup properly or that I'm not running Sixpack properly. I'm coming for a Node/Javascript environment where we use something like `forever` to keep the Node process up and running all the time.

**Comment by zackkitzmiller** [comment]
You're definitely going to run into issues is production if you're not running gunicorn. Sixpack as it sits is single threaded.

**Comment by russelltaylor05** [comment]
@zackkitzmiller ok cool. I'll get that setup and see if it solves the problem. Thanks for the quick feedback.

**Comment by zackkitzmiller** [comment]
No problem. Let us know if you run into anything else. I'm going to close this for now, but feel free to re-open if you run into more performance issues.

**Comment by russelltaylor05** [comment]
@zackkitzmiller forgive my newbness when it comes to python and gunicorn, but I'm not able to access the server once I run using gunicorn.

I specified the server to run on port 5001, but it looks like gunicorn in running on port 8000. I've tried both with no response.

```
ubuntu@ip-172-30-2-187:~$ gunicorn --access-logfile - -w 8 --worker-class=gevent sixpack.server:start
[2016-05-05 18:10:47 +0000] [1900] [INFO] Starting gunicorn 19.4.1
[2016-05-05 18:10:47 +0000] [1900] [INFO] Listening at: http://127.0.0.1:8000 (1900)
[2016-05-05 18:10:47 +0000] [1900] [INFO] Using worker: gevent
[2016-05-05 18:10:47 +0000] [1905] [INFO] Booting worker with pid: 1905
[2016-05-05 18:10:47 +0000] [1907] [INFO] Booting worker with pid: 1907
[2016-05-05 18:10:47 +0000] [1909] [INFO] Booting worker with pid: 1909
[2016-05-05 18:10:48 +0000] [1911] [INFO] Booting worker with pid: 1911
[2016-05-05 18:10:48 +0000] [1913] [INFO] Booting worker with pid: 1913
[2016-05-05 18:10:48 +0000] [1915] [INFO] Booting worker with pid: 1915
[2016-05-05 18:10:48 +0000] [1917] [INFO] Booting worker with pid: 1917
[2016-05-05 18:10:48 +0000] [1919] [INFO] Booting worker with pid: 1919
```

I've also opened up all these ports on my EC2 box:

![image](https://cloud.githubusercontent.com/assets/2423220/15052442/8f386cb0-12b2-11e6-8fc4-ac5dc4ab02d1.png)

Any help would be appreciated.

**Comment by russelltaylor05** [comment]
@zackkitzmiller I've got Gunicorn up and running, but it seems that sixpack-web isn't reading properly from the sixpack-server.

Here is how i'm running both: 

```
gunicorn -b 0.0.0.0:8080 --access-logfile - -w 8 --worker-class=gevent sixpack.server:start &
gunicorn -b 0.0.0.0:8000 --access-logfile - -w 2 --worker-class=gevent sixpack.web:start &
```

I can ping the server with `http://52.90.248.164:8080/participate?client_id=64935fe6-ac98-4447-a26f-4840c6956eb0&experiment=homepage-layout&alternatives=original&alternatives=variation` and I get the proper response back.

But, when I try to visit sixpack web at `http://52.90.248.164:8000/` I get this: 

![image](https://cloud.githubusercontent.com/assets/2423220/15053579/2046348a-12b8-11e6-9ab8-d4232dbbfad4.png)

Obviously there is any issue with loading the static CSS files, but it also should be showing experiment data, which it doesn't seem to be recognizing

Do I need to be passing the sixpack.yml config file in someway? Thats the only thing I see missing at the moment.
