### ISSUE TITLE
Gunicorn Setup Issues

### ISSUE THREAD

**Issue by russelltaylor05** [seatgeek/sixpack#230]
I've got Gunicorn up and running, but it seems that sixpack-web isn't reading properly from sixpack-server.

Here is how i'm running both: 

```
gunicorn -b 0.0.0.0:8080 --access-logfile - -w 8 --worker-class=gevent sixpack.server:start &
gunicorn -b 0.0.0.0:8000 --access-logfile - -w 2 --worker-class=gevent sixpack.web:start &
```

I can ping the server with `http://52.90.248.164:8080/participate?client_id=64935fe6-ac98-4447-a26f-4840c6956eb0&experiment=homepage-layout&alternatives=original&alternatives=variation` and I get the proper response back.

But, when I try to visit sixpack web at `http://52.90.248.164:8000/` I get this: 

![image](https://cloud.githubusercontent.com/assets/2423220/15053579/2046348a-12b8-11e6-9ab8-d4232dbbfad4.png)

Obviously there is any issue with loading the static CSS files, but it also should be showing experiment data, which it doesn't seem to be recognizing

Do I need to be passing the sixpack.yml config file in someway? Thats the only thing I see missing from the `gunicorn` command when I compare it to the `SIXPACK_CONFIG=<path to config.yml> sixpack` comand.

**Comment by josegonzalez** [comment]
@russelltaylor05 did you figure this out? I think you just have to set that env var for gunicorn, same as you would for sixpack.

**Comment by russelltaylor05** [comment]
ended up going this route and the setup seems to be working for me. https://gist.github.com/Valve/1ca13fc29ab8cb58b23d
