### ISSUE TITLE
Timeout Issues in Production

### ISSUE THREAD

**Issue by russelltaylor05** [seatgeek/sixpack#232]
I've got a production instance of Sixpack up and running and I'm trying to run an A/A test to make sure everything is working properly. My problem is that somewhere around 20% of my client request are returning with timeout errors. Any advice would be greatly appreciated.

Here are the details on my setup. I followed this [production installation guide](https://gist.github.com/Valve/1ca13fc29ab8cb58b23d) for the most part:

 - I'm running Sixpack server on an t2.large EC2 instance. I initially was running on a t2.micro, but upgraded to the t2.large in hopes of fixing the timeout issues, no luck.
 - The page I'm testing gets around 5,000 pageviews a day, so that is roughly how many participate calls I'm making to the Sixpack Server
 - I'm using the Sixpack Javascript client to send participation request to the Sixpack Server 
 - I Increase the `timeout` default config to 3000ms in the javascript client to help reduce timeout errors, it helped a little, but still seeing way to many errors.

### Client Participate Request
```javascript
var session = new sixpack.Session({
  base_url: 'https://sixpack.cssmenumaker.com',
  cookie_domain: '.' + window.location.hostname,
  timeout: 3000
});
session.participate("homepage-layout", ["original", "variation"], function (err, res) {
  analytics.ready(function() {        
    if (err) {     
      console.log(err);
      analytics.track('Sixpack error'); 
      throw err;
    }
    if (res.status == 'failed') {
      console.log(res, err);
      analytics.track('Sixpack Error', {
        msg: res.error.message
      });
    }
    analytics.track('Viewed Homepage');
  });
});
```
### /etc/supervisor/conf.d/sixpack.conf
```
[program:sixpack]
command=gunicorn sixpack.server:start --bind unix:/tmp/sixpack.sock -w 5 --access-logfile /var/log/sixpack/gunicorn-access.log
autostart=true
autorestart=true
stdout_logfile = /var/log/sixpack/supervisor-sixpack.log              ; Where to write log messages
redirect_stderr = true                                                ; Save stderr in the same log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8                       ; Set UTF-8 as default encoding
```

###  /etc/nginx/nginx.conf
```
user www-data;
# make it equal to number of cores * number of CPUs
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 1024;
}

http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        include /etc/nginx/sites-enabled/*;
}
```

### /etc/nginx/sites-available/sixpack
```
upstream sixpack {
        # fail_timeout=0 means we always retry an upstream even if it failed
        # to return a good HTTP response (in case the Unicorn master nukes a
        # single worker for timing out).
        server unix:/tmp/sixpack.sock fail_timeout=0;
}
server {
        listen 80 default;
        location / {
                proxy_pass http://sixpack;
        }
}
```

**Comment by josegonzalez** [comment]
Do you have logs of sixpack timing out on web requests from nginx or supervisord? We optionally have support for sending metrics to statsd which might help you debug your production performance issues.

**Comment by russelltaylor05** [comment]
@josegonzalez Thanks for the quick response. I don't seem to be finding anything helpful in the logs. I've checked:

#### /var/log/sixpack/gunicorn-access.log

I don't see anything suspicious here. I even setup a script to do 300 concurrent requests, essentially overloading the server. My NodeJS script shows timeout errors, but the logs only show status code 200 requests.

Some entries:
```
199.27.128.63 - - [09/May/2016:00:51:13 +0000] "GET /participate?client_id=582381fe-6f05-4cd4-91d1-3141ced13308&experiment=testing&alternatives=original&alternatives=variation HTTP/1.1" 200 142 "-" "-"
199.27.128.63 - - [09/May/2016:00:51:13 +0000] "GET /participate?client_id=34ceb4e6-2a22-41d6-8002-de1c0493a6a1&experiment=testing&alternatives=original&alternatives=variation HTTP/1.1" 200 141 "-" "-"
199.27.128.63 - - [09/May/2016:00:51:13 +0000] "GET /participate?client_id=0e61a258-5ded-4171-bfd1-54fc85077c8d&experiment=testing&alternatives=original&alternatives=variation HTTP/1.1" 200 142 "-" "-"
```

#### /var/log/nginx/access.log
Looks to be identical to the gunicorn-access.log. 

#### /var/log/nginx/error.log
Nothing here, empty file.


My thoughts are that maybe there is something up with the Client Side Javascript library. This is the code that throws the timeout error:

```
    var _request = function(uri, params, timeout, callback) {
        var timed_out = false;
        var timeout_handle = setTimeout(function () {
            timed_out = true;
            return callback(new Error("request timed out"));
        }, timeout);
```

It seems to me that maybe request are just be returned slow and the client is throwing a timeout error event though the Sixpack server is returning a succesfull 200 response. 

I've also noticed that when using the Javascript Client Library in the browser, that it doesn't return proper error messaging. 

For example, the javascript client returns a generic `request timed out` error while a curl request of the same url will give an error like this:

```
sixpack.callback2({"status": "failed", "message": "this client was not participating"})
```

I'm honestly not quite sure whether the problem is on the Server of the Client side. Any thoughts?

One thing that would help me debug would be if I could make HTTP Get/Post request to the Sixpack server from my browser side javascript via CORS. It looks like that is restricted at the moment. I think I could get more detailed responses this way. 

Do you know how to turn on CORS for the Sixpack Server?

**Comment by josegonzalez** [comment]
We turn on CORS via the nginx server. 

Honestly if the requests aren't even getting to your nginx layer - and it seems like they aren't - it is probably something upstream that is screwing around here.

**Comment by josegonzalez** [comment]
Closing as this seems like a bug in your infrastructure, external to sixpack.
