### ISSUE TITLE
how to set config.yml when use gunicorn and gevent

### ISSUE THREAD

**Issue by niuhp** [seatgeek/sixpack#234]
when use gunicorn like
gunicorn --access-logfile - -w 8 --worker-class=gevent sixpack.server:start
how can I set the config.yml file?

**Comment by josegonzalez** [comment]
As documented in our [readme](https://github.com/seatgeek/sixpack#getting-started), you can specify it as an environment variable:

```
SIXPACK_CONFIG=path/to/config.yml gunicorn --access-logfile - -w 8 --worker-class=gevent sixpack.server:start
```
