### ISSUE TITLE
deleted keys from redis, broke dashboard

### ISSUE THREAD

**Issue by mdressman** [seatgeek/sixpack#236]
Hello! I've been meaning to followup and let you know that we've been running many experiments with Sixpack and things have been going pretty well.

We recently came up against some memory issues so we manually deleted keys related to archived experiments in redis. In hindsight, I should've used the web delete api, but now we're in a bit of a pickle.

Our dashboards are borked, I can view individual experiment details but the list views are returning 500s. I assume we broke something with the `Experiment.all()` calls trying to get a list of all experiments when we deleted the keys from the db.

Any ideas or advice on how to fix the dashboard views? Greatly appreciated, thanks.

**Comment by josegonzalez** [comment]
Without error logs or anything, not much we can do here. You could dry just running a flushdb to clear your state if you don't have any tests running at the moment.

**Comment by mdressman** [comment]
thanks for the quick response!  nothing too helpful in the dashboard logs:

```
10.240.0.104 - - [18/May/2016 20:20:59] "GET / HTTP/1.1" 500 -
10.44.17.1 - - [18/May/2016 20:20:59] "GET /_status HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by josegonzalez** [comment]
This looks like maybe you just can't talk to your redis instance, as the socket is failing to send.

**Comment by tylerd-porch** [comment]
@josegonzalez I can prove the dashboard can talk to the redis server:
```
root@sixpack-dashboard-0:/#  telnet sixpack-redis.default.svc.cluster.local 6379
Trying 10.7.246.241...
Connected to sixpack-redis.default.svc.cluster.local.
Escape character is '^]'.
MONITOR
+OK
+1463605637.283511 [15 10.4.1.7:60611] "PING"
+1463605638.906519 [15 10.4.7.12:39706] "PING"
^]
telnet> quit
Connection closed.
```

**Comment by mdressman** [comment]
hmm, no problem talking to redis. i can access `/experiments/detail` view

but it blows up on the list pages of either active or archived.

are there any other places we need to touch / delete to totally wipe an experiment beyond the matching keys from redis?

**Comment by josegonzalez** [comment]
What exactly did you delete?

**Comment by mdressman** [comment]
`redis-cli --raw keys "*experiment-name*" | xargs redis-cli del`

**Comment by josegonzalez** [comment]
It's also a member of the experiments set, `sixpack:e` I think.

**Comment by mdressman** [comment]
ah, good call, i manually removed the affected members from the `sixpack:e` set.  still broken.  any other ideas?  really appreciate the help @josegonzalez

**Comment by josegonzalez** [comment]
Can you run gunicorn with the `--preload` option? That seems to not swallow errors as much. Would like to see a better stacktrace.

**Comment by mdressman** [comment]
hmm, just ran the dashboard in debug mode 

`ValueError: experiments require at least two alternatives`

![image](https://cloud.githubusercontent.com/assets/684390/15377174/7fc27ce2-1d0e-11e6-99de-64dd8335fea6.png)

**Comment by mdressman** [comment]
🍰 🍦 🌠 

fixed! debug mode was super helpful to be able to dump() local variables at the point of failure.

removing members from the `sixpack:e` set did the trick

thanks @josegonzalez
