### ISSUE TITLE
Feature Request: Ability to change the Traffic Fraction from the Web UI

### ISSUE THREAD

**Issue by bfmnorman** [seatgeek/sixpack#242]
It would be awesome if we could increase the Traffic Fraction from the Web UI. If all new experiments were created with a reasonable default (say 10% or even configurable via a config variable), then the web UI could be used to increase the percent of traffic in the test.

The issue with the current solution is that any change in traffic percentage has to be made in the code that's sending the participate calls.

**Comment by oebabaluba** [comment]
I would like to see this feature too! +1

**Comment by josegonzalez** [comment]
The whole point of sixpack is to drive your tests from code, not from a web ui. As such, any changes to traffic_fractions *must* happen in code. Implementing this feature is out of the scope of sixpack, and we recommend you look into other projects for such a thing.

**Comment by nikrolls** [comment]
@josegonzalez I would argue that traffic fractions in the UI is a very useful feature even for a platform that's designed to be driven from the code. Being able to change the traffic fraction over the lifetime of an experiment is critical for risky experiments or features that need to be slowly rolled out or temporarily disabled (eg, out of business hours). Requiring a code deploy or to manage a configuration variable on the platform side makes far less sense to me than making it available in the Sixpack dashboard.

**Comment by josegonzalez** [comment]
@nikrolls I understand your desires here but thats simply not one of the goals of this project. As as I said before, the point of sixpack is to drive your tests from code and not from a web ui.
