### ISSUE TITLE
Revenue tracking

### ISSUE THREAD

**Issue by jmagnuss** [seatgeek/sixpack#243]
From the original blog post:

> As a company we aren’t only interested in absolute conversions; we’re interested in revenue too. Thus, the next Sixpack release will allow you to pass a revenue value with each conversion which sixpack-web will use to determine a revenue-optimized winner of the experiment.

Did anything come of this?  I see the `value` field in the API response, but don't see anything else related to it.

**Comment by josegonzalez** [comment]
This wasn't ever really worked on, and I'd like to track any work for it in #44.
