### ISSUE TITLE
Use planout API instead of copy/paste algorithms

### ISSUE THREAD

**Issue by lucasbm88** [seatgeek/sixpack#265]
The sixpack project did a good choice when it decided to use planout random algorithm instead of creating a new one. However the algorithm was "ported", it means that the code was copied and pasted (with the owed credits). Planout is in constant development, and since sixpack was created the uniform_choice algorithm was modified and also new algorithms were added, e.g. weighted_choice. 

In order to keep up with planout evolution, sixpack should import planout as a module and use it's algorithms API, instead of copying/pasting the code.

**Comment by josegonzalez** [comment]
We're almost certainly not going to do this on our end. If you'd like to refactor sixpack to add this functionality, feel free to, but it currently solves our needs.
