### ISSUE TITLE
CSS link href is unknown

### ISSUE THREAD

**Issue by ShaneBurkhart** [seatgeek/sixpack#267]
I have installed sixpack using pip and I'm running the latest version.  I can create experiments with the API, but my CSS isn't loading for the dashboard.  It says "(unknown)" for the href.  I can see the dashboard's HTML.  It just appears ASSET_URL isn't defined.

I checked to see if the bundled CSS and JS were getting created.  They are being generated in the correct folder from the config.yml file.  I can also access them from the web if I navigate to the CSS file directly.  

So as far as I can tell, everything is working, but the URL for the CSS isn't being added in the dashboard template.  Do you have any ideas on why that would be?

I am using gunicorn, but I got the same results when running it with the "sixpack-web" command.  And I'm not getting any errors. I also have a secret key.

**Comment by ShaneBurkhart** [comment]
I ran it from source and it worked.  I'm not sure what wasn't working when installing with pip.  I'll close this.  Thanks.

**Comment by Valve** [comment]
@ShaneBurkhart can this be reopened please? Latest version from PIP is still broken
