### ISSUE TITLE
[Documentation low priority] - Experiment names can only be lowercase

### ISSUE THREAD

**Issue by aldrinabastillas** [seatgeek/sixpack#269]
**Issue:**
The README on the main repo states that 

> Valid experiment names must be alphanumeric and can contain _ and -.

while all the clients and the CLIENTSPEC only allow lowercase characters with the following regex, 

> ^[a-z0-9][a-z0-9\-_ ]*$

**Action:**
Update the main README =)

**Comment by josegonzalez** [comment]
Mind making a pr to clear that up?

**Comment by aldrinabastillas** [comment]
Done!
